source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target :NatriumExampleProject do
    pod 'Natrium'
end

target :NatriumExampleProject2 do
    pod 'Natrium'
end

post_install do |installer|
    system("Pods/Natrium/bin/natrium install --silent-fail")
end
