source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def install_natrium
  pod 'Natrium', :git => 'https://github.com/e-sites/Natrium.git', :branch => 'master'
end

target :NatriumExampleProject do
    install_natrium

    target 'NatriumExampleProjectTests' do
        inherit! :search_paths
    end
end

target :NatriumExampleProject2 do
    install_natrium
end


post_install do |installer|
    system("Pods/Natrium/bin/natrium install --silent-fail")
end
