import Foundation

/// Natrium.Config.swift
/// Autogenerated by natrium
///
/// - see: https://github.com/e-sites/Natrium

class Natrium {

    enum Environment: String {
        case staging = "Staging"
        case production = "Production"
    }

    enum Configuration: String {
        case debug = "Debug"
        case release = "Release"
    }

    struct Config {
        static let configuration: Configuration = .debug
        static let environment: Environment = .production

        static let testVariableBoolean: Bool = true
        static let nilVariable: String? = nil
        static let testVariableDouble: Double = 5.5
        static let testVariableString: String = "debugStringExampleProject2"
        static let testVariableInteger: Int = 555
    }
}