import Foundation

/// Natrium.Config
/// Autogenerated by natrium
///
/// - see: https://github.com/e-sites/Natrium

open class AppConfig {
    public enum EnvironmentType: String {
        case staging = "Staging"
        case production = "Production"
    }

    public enum ConfigurationType: String {
        case debug = "Debug"
        case release = "Release"
    }

    public static let environment: EnvironmentType = .production
    public static let configuration: ConfigurationType = .debug

    open static let testVariableDouble: Double = 5.5
    open static let testVariableBoolean: Bool = false
    open static let testVariableInteger: Int = 125
    open static let nilVariable: String? = nil
    open static let testVariableString: String = "debugString"
}
