/// NatriumConfig.m
/// Autogenerated by natrium
///
/// - see: https://github.com/e-sites/Natrium

#import "NatriumConfig.h"

@implementation NatriumConfig
+ (EnvironmentType)environment {
    return EnvironmentTypeProduction;
}

+ (ConfigurationType)configuration {
    return ConfigurationTypeDebug;
}

+ (CGFloat)testVariableDouble {
    return 5.5;
}

+ (BOOL)testVariableBoolean {
    return NO;
}

+ (NSInteger)testVariableInteger {
    return 125;
}

+ (NSObject *)nilVariable {
    return NULL;
}

+ (NSString *)testVariableString {
    return @"debugString";
}

@end

