import Foundation

/// Natrium.Config.swift
/// Autogenerated by natrium
///
/// - see: https://github.com/e-sites/Natrium

class Natrium {

    enum Environment: String {
        case staging = "Staging"
        case production = "Production"
    }

    enum Configuration: String {
        case debug = "Debug"
        case release = "Release"
    }

    class Config {
        static let environment: Natrium.Environment = .production
        static let configuration: Natrium.Configuration = .debug
        static let testVariableBoolean: Bool = false
        static let testVariableDouble: Double = 5.5
        static let nilVariable: String? = nil
        static let testVariableString: String = "debugString"
        static let testVariableInteger: Int = 125
    }
}
