--- 
environments: 
  - Staging
  - Production

appicon: 
  appiconset: NatriumExampleProject/Assets.xcassets/AppIcon.appiconset
  idioms: 
    - iphone
    - ipad
  original: icon.png
  ribbon: 
    Production: 
      Debug: PRODUCTION
      Release: ""
    Staging: STAGING

files: 
  Files/file.html: 
    Production: Files/file-production.html
    Staging: Files/file-staging.html

launch_screen_versioning: 
  enabled: true
  labelName: LaunchScreenVersionLabel
  path: NatriumExampleProject/Base.lproj/LaunchScreen.storyboard

natrium_variables: 
  SomeOtherVar: false
  ChangeTargetVariable: original_value

plists: 
  NatriumExampleProject/Info.plist: 
    CFBundleDisplayName: 
      Production: App
      Staging: App_staging

target_specific: 
  NatriumExampleProject2: 
    appicon: 
      original: icon2.png
    natrium_variables: 
      ChangeTargetVariable: 
        Staging: target2_value_staging
        Production:
          Debug: target2_value_production_debug
          Release: target2_value_production_release
    plists: 
      NatriumExampleProject/Info.plist: 
        CFBundleDisplayName: "App #2"
    variables: 
      testVariableBoolean: true
      testVariableInteger: 
        "*": 
          Debug: 555
          Release: 666
    xcconfig: 
      PRODUCT_BUNDLE_IDENTIFIER: 
        Production: 
          Release: com.esites.app.two2

variables: 
  envUser: "#env(USER)"
  natriumEnvFileVariable: "#env(ENV_VARIABLE_TEST)"
  nilVariable: null
  testVariableBoolean: false
  testVariableDouble: 
    Production: 5.5
    Staging: 1.0
  testVariableInteger: 125
  testVariableString:  "#{ChangeTargetVariable}"

xcconfig: 
  PRODUCT_BUNDLE_IDENTIFIER: 
    Production: 
      Debug: com.esites.app.production
      Release: "com.esites.app.#{DebugString}"
    Staging: com.esites.app.staging
